### ISSUE TITLE
(編集ミス?) np.abs()の説明が複素共役になっている

### ISSUE THREAD

**Issue by atsushieno** [masahitotogami/python_source_separation#3]
本文P.41のcode 2.8 NumPyを用いた複素数の四則演算 のコメント部分ですが、次のようになっています:

![image](https://user-images.githubusercontent.com/53929/99039096-10c68800-25ca-11eb-98df-2a967fa0a562.png)

このリポジトリでいえばこの部分です。

https://github.com/masahitotogami/python_source_separation/blob/42b9c1eab00c6ba2b204e7986b25ed981ed3c1ca/section2/sample_code_c2_7.py#L23

この後者は「絶対値を表示する」の意図でしょうか?　複素数をきちんと理解しているわけではないのですが、`|x+jy|`は複素共役`x-jy`にはならなそうに思えます。

**Comment by masahitotogami** [comment]
ご指摘大変ありがとうございます。「絶対値を表示する」の誤植になります。謹んでお詫び申し上げます。
