### ISSUE TITLE
ソースコードの誤記? (2章5節、スペクトルサブトラクションによる雑音抑圧)

### ISSUE THREAD

**Issue by smalltech-bw** [masahitotogami/python_source_separation#5]
PDF版で読ませていただいております。下記、若干混乱した部分があったためご連絡いたします。

テキスト上code2.14の「#雑音の振幅を推定」という部分で、全体を1/2乗するコードになっています。

GitHub上では1/p乗するコードになっています。
https://github.com/masahitotogami/python_source_separation/blob/master/section2/sample_code_c2_13.py
(2.13となっていますがおそらくこれがcode2.14に対応していると思います)

中でp乗していることから1/p乗の方が正しいかと思っておりますが念のためご連絡いたします。
(テキスト上の式[2.46]では「中で2乗、全体を1/2乗」になっています)

**Comment by masahitotogami** [comment]
ご指摘大変ありがとうございました。

誤植（https://github.com/masahitotogami/python_source_separation/blob/master/errata.md)に２件記載しました。
式[2.46]が誤っており、25番目の誤植として修正内容記載しています。また、テキストのcode2.14の内容に誤植があり、26番目の誤植として記載しております。GitHub上でのコードが正しいコードとなります。
